export const PROCESSOS_COMPLIANCE = [
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.1",
    "processo": "Relatório Mensal de Gestão (RMG) - Faturamento Mensal do Volume de Água",
    "fundamentacao": "Cláusula 6.2 e 6.5 do Contrato de Interdependência",
    "fluxo": "DPRQ → GRMC → SFCC → GAPR",
    "destino": "Concessionária",
    "prazo": "Mensalmente, até o 10º dia do mês subsequente.",
    "impacto": "Suspensão do fluxo de caixa; multas moratórias.",
    "entregaveis": "(DPRQ): Relatório Mensal contendo a totalização dos volumes entregues e as memórias de cálculo dos Indicadores de Desempenho (IQA, ISP, DMP), conforme Processos 2.1 e 2.3. (GRMC): Cruzamento dos dados operacionais com penalidades regulatórias e cálculo matemático da Equação D, simulando o valor do desconto financeiro. (SFCC): Emissão da Fatura Comercial processando eventuais deduções e multas validadas pela GRMC. Saída (GAPR): Envio formal da Fatura Comercial e do Relatório Mensal de Gestão validado para a Concessionária."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.2",
    "processo": "Resolução de Divergência de Macromedidores (> 5 %)",
    "fundamentacao": "Cláusula 7.7.3 e 7.7.4 do Contrato de Interdependência",
    "fluxo": "SQCO / SPRO → GECO → GRMC → GAPR",
    "destino": "AGRESE (mediação) / Concessionária",
    "prazo": "Por demanda, sempre que a discrepância na leitura exceder 5%.",
    "impacto": "Concessionária paga apenas o menor volume apurado até a decisão da AGRESE. Perda de receita imediata.",
    "entregaveis": "(SQCO/SPRO): Relatório Técnico de Divergência de Medição anexando laudos de calibração e de vida útil dos macromedidores próprios que apresentaram divergências. (GECO): Instrução jurídica da controvérsia. (GRMC): Nota Técnica baseando o pleito de recuperação de receita, afastando falha da DESO.  Saída (GAPR): Ofício de instauração de mediação arbitral na AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.3",
    "processo": "Cálculo e Pleito de Reajuste Tarifário (IRC)",
    "fundamentacao": "Cláusula 6.3 e 6.4 do Contrato de Interdependência",
    "fluxo": "GRMC → GAPR",
    "destino": "AGRESE (Homologação)",
    "prazo": "12 meses depois do último reajuste.",
    "impacto": "Defasagem tarifária e corrosão da margem líquida.",
    "entregaveis": "(GRMC): Cálculo de Índice de Reajuste Contratual e nova tarifa com base em indicadores macroeconômicos e emissão de pleito. Saída (GAPR): Envio do Pleito de Reajuste submetido à AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.4",
    "processo": "Revisão Extraordinária da Tarifa",
    "fundamentacao": "Cláusula 19.1 do Contrato de Produção de Água",
    "fluxo": "GCIG / SPGE / SFCC → GRMC → GAPR",
    "destino": "AGRESE / Poder Concedente",
    "prazo": "Por demanda, diante de desequilíbrio materializado.",
    "impacto": "Inviabilidade da operação estrutural.",
    "entregaveis": "Trata-se de um dos mecanismos para recomposição do equilíbrio econômico-financeiro. Observar o rito do Processo 4.4."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.5",
    "processo": "Recolhimento da Taxa de Fiscalização",
    "fundamentacao": "Cláusula 14.10.3 do Contrato de Produção de Água",
    "fluxo": "GRMC → GFIN → GAPR",
    "destino": "AGRESE",
    "prazo": "Mensalmente, até o 10º dia útil.",
    "impacto": "Inadimplência regulatória; juros, multas e caducidade.",
    "entregaveis": "(GRMC): Identifica o faturamento líquido do mês imediatamente anterior (Processo 1.1), aplica-se alíquota de 0,5% sobre o faturamento líquido e confere com a guia de recolhimento emitida pela AGRESE, para certificação de conformidade fiscal-regulatória.  (GFIN): Efetua o pagamento e emite o respectivo comprovante até o 10º dia útil de cada mês. Saída (GAPR): Guia de recolhimento paga com comprovante encaminhada a AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.6",
    "processo": "Relatório Anual da Taxa de Fiscalização",
    "fundamentacao": "Cláusula 14.10.4  do Contrato de Produção de Água",
    "fluxo": "GRMC → GAPR",
    "destino": "AGRESE",
    "prazo": "Anualmente, até o dia 05 de janeiro.",
    "impacto": "Sanção administrativa.",
    "entregaveis": "(GRMC): Extrato financeiro anual demonstrando o somatório algébrico das receitas vs. taxas pagas. Saída (GAPR): Relatório Anual consolidado protocolado."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.7",
    "processo": "Relatório Operacional Anual (ROA)",
    "fundamentacao": "Cláusula 14.7.1 e 14.7.1.1 do Contrato de Produção de Água",
    "fluxo": "DTEC → SFCC → GRMC / DPRQ → GRMC / SPGE → GRMC / GRMC → GAPR",
    "destino": "AGRESE / Poder Concedente",
    "prazo": "Anualmente, até o último dia de março.",
    "impacto": "Infração contratual direta e obstrução da contabilização da Base de Ativos (BAR), bloqueando ressarcimentos futuros de CAPEX.",
    "entregaveis": "(DTEC): Inventário de obras e investimentos concluídos e em andamento. (SFCC): Memórias de depreciação e amortização de ativos. (DPRQ): Relatório operacional com balanço hídrico anual e os indicadores de desempenho. (SGPE): Relatório de Compliance Social - PCD, com censo demográfico corporativo. (GRMC): Auditoria da coerência do relato operacional contra as exigências contratuais. Saída (GAPR): Protocolo do ROA oficial na AGRESE e no Poder Concedente."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.8",
    "processo": "Submissão das Demonstrações Financeiras",
    "fundamentacao": "Cláusulas 17.2.19 a 17.2.21 do Contrato de Produção de Água",
    "fluxo": "SFCC / Auditoria Independente Externa → GRMC  → GAPR",
    "destino": "AGRESE",
    "prazo": "Anualmente, até o dia 01º de maio.",
    "impacto": "Risco de multa e decretação de intervenção por falta de transparência.",
    "entregaveis": "(SFCC): Demonstrações contábeis e notas explicativas finalizadas com parecer de auditoria independente sem ressalvas. (GRMC): Conferência de exigências e prazos de publicação. Saída (GAPR): Publicação e protocolo das demonstrações na AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.9",
    "processo": "Assunção de Encargos por Inadimplência",
    "fundamentacao": "Cláusulas 8.1, 8.2.3 e 8.2.4  de Contrato de Interdependência",
    "fluxo": "SFCC / SPGE → GRMC → GAPR → AGRESE → GAPR → Concessionária",
    "destino": "Concessionária / AGRESE",
    "prazo": "Na ocorrência; e em até 2 dias úteis após anuência da AGRESE (até 30 dias para manifestação).",
    "impacto": "Risco da Concessionária assumir pagamentos com dedução coercitiva imediata na fatura da água. Risco de repasse de custos em reequilíbrio.",
    "entregaveis": "(SFCC): Dossiê crítico de notas fiscais vencidas contendo fundamentação normativa da insolvência e parecer contábil de crise. A SPGE deve modelar o impacto de reequilíbrio negativo se o gasto superar a fatura. (GRMC): Emissão de alerta detalhando probabilidade de bloqueio de contas e solicitação de anuência à AGRESE. Saída (GAPR): 1. Solicitação de anuência da AGRESE; e 2. Autorização oficial de Assunção de Encargos por Inadimplência enviada à Concessionária (após anuência)."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.10",
    "processo": "Regularização Imobiliária de Ativos Legados",
    "fundamentacao": "Cláusula 21.3.17 do Contrato de Produção de Água",
    "fluxo": "DTEC / SGAT →  SJUR → SFCC → GRMC → GAPR",
    "destino": "AGRESE / BAR",
    "prazo": "Contínuo.",
    "impacto": "Inviabilidade de licenciamentos ambientais futuros; incorreta contabilização e prejuízos na Base de Ativos Regulatória (BAR).",
    "entregaveis": "(DTEC/SGAT): Relatórios estruturados de titularidade formal sobre áreas de ETA’s e adutoras pré-existentes. (SJUR): Ações jurídicas e técnicas para regularização documental. (SFCC): Averbação patrimonial/contábil dos ativos. (GRMC): Análise de conformidade regulatória. Saída (GAPR): Submissão à AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.11",
    "processo": "Inventário Físico, Inspeção, Tagueamento, Conciliação Físico-Contábil e Consolidação da Base de Ativos Regulatória (BAR)",
    "fundamentacao": "Instrução Normativa ANA nº 01/2024, Norma de Referência ANA nº 03/2023, Norma de Referência ANA nº 06/2024",
    "fluxo": "-",
    "destino": "-",
    "prazo": "-",
    "impacto": "-",
    "entregaveis": "AGRESE Etapa Preliminar do Projeto BAR (Planejamento). Rejeição sistêmica de laudos avaliatórios futuros por ausência de rastreabilidade contábil interna auditável; aplicação de multas. (Consultoria Especializada): Planejamento para execução do Manual de Controle Patrimonial (Projeto BAR). (SFCC/SGAT/GTIC): Promovem o alinhamento contábil, físico e tecnológico com base no planejamento da Consultoria, preparando e fornecendo os dados necessários.  (Consultoria/SFCC/SGAT/GTIC): Manual técnico exaustivo descrevendo políticas contábeis imobilizadas, métricas estipuladas de vida útil por classe hídrica de ativo, e arquitetura de árvore de ativos padronizada e compatível com os sistemas de informação da Companhia, obedecendo as normas regulamentadoras da ANA. (GRMC): Análise de conformidade para pleito de parecer regulatório aprovando o Manual de Controle Patrimonial. Saída (GAPR): Submissão do Manual à AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.11.1",
    "processo": "Manual de Controle Patrimonial (MCP)",
    "fundamentacao": "Instrução Normativa ANA nº 01/2024, Norma de Referência ANA nº 03/2023, Norma de Referência ANA nº 06/2024",
    "fluxo": "Consultoria Especializada → SFCC / SGAT / GTIC → GRMC → GAPR",
    "destino": "AGRESE",
    "prazo": "Fase 1 do Projeto BAR.",
    "impacto": "Rejeição sistêmica de laudos avaliatórios futuros por ausência de rastreabilidade contábil interna auditável; aplicação de multas.",
    "entregaveis": "(Consultoria Especializada): Planejamento para execução do Manual de Controle Patrimonial (Projeto BAR). (SFCC/SGAT/GTIC): Promovem o alinhamento contábil, físico e tecnológico com base no planejamento da Consultoria, preparando e fornecendo os dados necessários. (GRMC): Análise de conformidade para pleito de parecer regulatório aprovando o Manual de Controle Patrimonial. Saída (GAPR): Submissão do Manual à AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.11.2",
    "processo": "Inventário Físico, Inspeção e Tagueamento",
    "fundamentacao": "Instrução Normativa nº 01/2024 da ANA; Cláusulas 14.1.8, 31.3 e 31.4 do Contrato de Produção de Água",
    "fluxo": "SGAT (liderança tática) / DPRQ / SFCC / Consultoria → SFCC / GTIC / Consultoria → GRMC → GAPR",
    "destino": "AGRESE",
    "prazo": "Fase 2 do Projeto BAR.",
    "impacto": "Glosas no faturamento, sanções por ineficiência, e rejeição de laudos pela fiscalização da AGRESE caso ativos sejam valorados com vida útil integral mas apresentem falhas/patologias omitidas.",
    "entregaveis": "(Consultoria/SGAT/DPRQ/SFCC): Relatório de Inventário de Campo englobando cobertura de infraestruturas Upstream e bens próprios, identificação de manifestações patológicas, fixação de tags/QR Code, mediante inspeção de campo, identificação física, georreferenciamento, coleta de dados técnicos, registro fotográfico e vinculação do ativo ao respectivo cadastro patrimonial e contábil. (Consultoria/SFCC/GTIC): Integração contábil e estruturação tecnológica do levantamento. (GRMC): Análise de conformidade para pleito de parecer regulatório aprovando o Inventário Integrado.  Saída (GAPR): Submissão do pleito à AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.11.3",
    "processo": "Conciliação Físico-Contábil e Teste de Impairment",
    "fundamentacao": "Pronunciamento CPC 01; NR 03/2023 da ANA; Cláusulas 14.1.8, 31.3 e 31.4 do Contrato de Produção de Água",
    "fluxo": "SFCC  (liderança tática) / SGAT / Consultoria → GRMC → GAPR",
    "destino": "AGRESE",
    "prazo": "Fase 3 do Projeto BAR. Anterior à formulação matemática dos cálculos VNR/CHC.",
    "impacto": "Efeito lesivo direto no processo tarifário pelo inflacionamento inverídico da base; anulação de pleitos indenizatórios.",
    "entregaveis": "(Consultoria/SGAT): Inventário atualizado com rastreabilidade das intervenções e as atualizações cadastrais técnicas dos ativos. (Consultoria/SFCC): Relatório analítico consolidado listando ativos físicos operantes não registrados na contabilidade (sobras) e bens escriturados já deteriorados e inexistentes. Parecer sobre teste de recuperabilidade de capital (Impairment). Necessidade de trilha atuarial segregada para ativos indenizáveis versus ativos não indenizáveis no fim da concessão. (GRMC): Solicitação de parecer regulatório validando a Conciliação Físico-Contábil e o Teste de Impairment. Saída (GAPR): Submissão à AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.11.4",
    "processo": "Consolidação da BAR - Emissão, Revisão e Defesa dos Laudos VNR e CHC",
    "fundamentacao": "NR 03/2023 e NR 06/2024 da ANA; Cláusulas 14.1.8 e 23.3 do Contrato de Produção de Água",
    "fluxo": "SGAT / SFCC / DPRQ / Consultoria → GTIC → GRMC → GAPR",
    "destino": "AGRESE",
    "prazo": "Marco final do ciclo executivo da BAR.",
    "impacto": "Confisco tácito de capital investido; impossibilidade material intransponível de fundamentar revisão tarifária extraordinária do IRC.",
    "entregaveis": "(Consultoria/SFCC/SGAT/DPRQ): Cadernos e planilhas integradas de modelagem orçamentária atestando o VNR/CHC individualizado para cada ativo (complexo de ETA, Poço, EEAB e malha de adutoras, etc.) assegurando segregação entre Bens Privados e Reversíveis. Instruídas com acervo técnico (SGAT), balancetes (SFCC) e registros operacionais (DPRQ). (GTIC): Bases de dados nativamente integradas ao sistema corporativo. (GRMC): Análise de conformidade para pleito de parecer regulatório certificando oficialmente a BAR. Saída (GAPR): Submissão à AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.12",
    "processo": "Integração Contínua e Atualização de Novos Ativos (CAPEX)",
    "fundamentacao": "Cláusula 14.1.8  do Contrato de Produção de Água",
    "fluxo": "SUEN / SGAT → SFCC → GTIC",
    "destino": "AGRESE",
    "prazo": "Até 30 dias após o ato de recebimento do ativo.",
    "impacto": "Rápida defasagem estrutural da Base de Ativos; perdas tarifárias irreparáveis decorrentes da não incidência temporal correta na linha de amortização.",
    "entregaveis": "(SUEN/SGAT): Relatório conclusivo de inspeção anexado ao cadastro técnico de As-Built e coordenadas (GIS) da nova infraestrutura imobilizada. (SFCC): Deflagração sistemática da amortização e depreciação na base de remuneração. (GTIC): Integração na base de dados da Companhia. (GRMC): Validação da conformidade do acervo técnico e documental com as diretrizes regulatórias e contratuais. (GAPR): Comunicação prévia AGRESE assegurando o lastro adequado e transparência perante a Agência Reguladora."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.13",
    "processo": "Pedido de Autorização Prévia para Desativação ou Alienação de Bens Reversíveis",
    "fundamentacao": "Cláusula 9.6, 9.6.1 e 9.6.2 do Contrato de Produção de Água",
    "fluxo": "DPRQ (Baixa Operacional) / SGAT (Parecer de Manutenção) → CAIP (Controle Contábil) → SJUR → GRMC → GAPR",
    "destino": "AGRESE",
    "prazo": "Antecedência razoável prévia à alienação, desmonte ou descarte, acompanhada de plano de reposição.",
    "impacto": "Dilapidação patrimonial presumida; infração regulatória gravíssima; imposição de multas rescisórias e inviabilização da atualização e contabilização da Base de Ativos (BAR).",
    "entregaveis": "(DPRQ/SGAT): Relatório de obsolescência mecânica do ativo, laudo de quebra insanável ou viabilidade de upgrade.(CAIP): Extrato de depreciação contábil do item. (SJUR): Validação do rito de desfazimento, assegurando que as modalidades de alienação planejadas para as sucatas e bens imprestáveis obedeçam estritamente à legislação administrativa de gestão patrimonial, afastando qualquer presunção legal de infração dolosa ou dilapidação de bens reversíveis. (GRMC): Análise de conformidade prévia. Saída (GAPR): Ofício de solicitação formal para autorização de baixa e desfazimento ou leilão de sucata encaminhado à AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.14",
    "processo": "Notificação de Assinatura, Emissão e Alteração de Contratos de Financiamento",
    "fundamentacao": "Cláusulas 13.3 e 13.5 do Contrato de Produção de Água",
    "fluxo": "GFIN / CTRT → GRMC → GAPR",
    "destino": "Poder Concedente",
    "prazo": "Até 10 dias úteis contados da data de assinatura dos acordos ou emissão dos títulos.",
    "impacto": "Risco de sanção por omissão de dados estruturais; invalidação regulatória de passivos.",
    "entregaveis": "(GFIN/CTRT): Cópia integral dos contratos de crédito, emissões de debêntures, relatórios financeiros ordinários encaminhados aos credores e documentos garantidores anexos. (GRMC): Análise de conformidade (sem oneração ilegal de bens reversíveis). Saída (GAPR): Ofício remetendo as cópias e certificação de conformidade."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.15",
    "processo": "Alerta de Inadimplência em Financiamentos ou Execução de Garantias",
    "fundamentacao": "Cláusula 13.4 do Contrato de Produção de Água",
    "fluxo": "SFCC → GCIG → GRMC → GAPR",
    "destino": "Poder Concedente",
    "prazo": "Até 1 dia útil após a configuração do descumprimento ou recebimento de notificação extrajudicial bancária.",
    "impacto": "Decretação iminente de Caducidade da outorga pelo Poder Concedente devido ao comprometimento da viabilidade econômico-financeira (Cláusula 26.3.1 do Contrato de Produção de Água).",
    "entregaveis": "(SFCC): Relatório circunstanciado do evento de inadimplência ou moratória. (GCIG): Análise e gestão do risco com proposição de medidas de contenção. (GRMC): Emissão de Nota Técnica Regulatória com exposição dos fatos e consequências regulatórias. Saída (GAPR): Ofício de alerta detalhando o descumprimento da cláusula de convenção financeira e o risco iminente de constrição dos recebíveis tarifários da Companhia."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.16",
    "processo": "Gestão Integrada de Apólices de Seguro, Franquias e Sinistros",
    "fundamentacao": "Cláusulas 21.3.34 e 21.3.35  do Contrato de Produção de Água",
    "fluxo": "GLIC / SFCC → GCIG",
    "destino": "GCIG",
    "prazo": "Contínuo (Alertas sistêmicos com 90 dias de antecedência do vencimento)",
    "impacto": "Absorção de todos os prejuízos materiais causados por eventos de Força Maior até o limite das franquias; decretação de infração contratual por descobertura de garantias.",
    "entregaveis": "(GLIC/SFCC): Inventário centralizado e atualizado de apólices de seguro (performance, responsabilidade civil cruzada, riscos de engenharia). (GCIG): Parametrização dos tetos de cobertura e emissão preventiva de alertas sistêmicos."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.17",
    "processo": "Certificação Prévia de Cláusulas de Sub-rogação em Contratos Terceirizados",
    "fundamentacao": "Cláusula 12.5 e 23.2.6 do Contrato de Produção de Água",
    "fluxo": "GLIC → GCIG",
    "destino": "GCIG / AGRESE (sempre que suscitada)",
    "prazo": "Ato antecedente à formalização das minutas e de novos contratos firmados pela GLIC.",
    "impacto": "Responsabilização civil solidária imposta à DESO por danos causados por entes terceirizados aos Bens Reversíveis.",
    "entregaveis": "(GLIC): Termos de Referência, Editais na íntegra e Minutas Contratuais contendo cláusulas pétreas e expressas que obrigam compulsoriamente a terceirizada a observar as regras rígidas de salvaguarda dos Bens Reversíveis, aceitando a figura do Poder Concedente como ente sucessor pleno. (GCIG): Compliance Check finalizado e ateste documental de liberação jurídica procedimental para veiculação do edital."
  },
  {
    "eixo": "Matriz Processual de Conformidade Regulatória e Financeira (Eixo 1)",
    "id": "1.18",
    "processo": "Governança sobre Segurança, Saúde Ocup. e Passivos Trabalhistas",
    "fundamentacao": "Cláusulas 21.3.8, 21.3.9 e 21.3.10 do Contrato de Produção de Água",
    "fluxo": "SGPE / GECO → GCIG",
    "destino": "GCIG",
    "prazo": "Contínuo / Mensal",
    "impacto": "Disputas ou embargos geram queda no desempenho e sanções contratuais graves.",
    "entregaveis": "(SGPE): Relatórios de indicadores de clima organizacional e de acidentalidade. (GECO): Relatórios analíticos de provisionamento judicial. (GCIG): Conversão dos dados e construção de matrizes preditivas de probabilidade de paralisação da operação."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Produção (Eixo 2)",
    "id": "2.1",
    "processo": "Gestão de Fornecimento de Volumes Mínimos (Take-or-Pay)",
    "fundamentacao": "Cláusula 10.1 do Contrato de Interdependência",
    "fluxo": "DPRQ → GRMC (Processo 1.1)",
    "destino": "Concessionária / AGRESE",
    "prazo": "Mensalmente, até o 5º dia do mês subsequente.",
    "impacto": "Multa de até 1% da fatura em prol da Concessionária se houver lucros cessantes (Equação D).",
    "entregaveis": "(DPRQ): Relatório Mensal com tabelas consolidadas de macromedição com a totalização volumétrica tratada matematicamente por ponto de entrega, calculando a relação entre Volume Ofertado e Planejado (VAO/VAP). Apuração primária de eventuais déficits mensais (VN). (GRMC): Conferência das deduções calculadas pela CONCESSIONÁRIA de eventuais deduções coercitivas (Equação D) relativas a falhas de fornecimento detectadas (Processo 1.1)."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Produção (Eixo 2)",
    "id": "2.2",
    "processo": "Análise e Revisão do Planejamento de Demanda",
    "fundamentacao": "Cláusulas 10.3 a 10.5 do Contrato de Interdependência",
    "fluxo": "SPGE / DTEC / DPRQ / DMES → GRMC → GAPR",
    "destino": "AGRESE / Concessionária",
    "prazo": "Em até 15 dias após o recebimento via AGRESE.",
    "impacto": "Imposição de ampliação coercitiva do CAPEX da DESO sem recomposição tarifária, caracterizando risco de subcapacidade ou assumindo o risco absoluto de expansão.",
    "entregaveis": "(SPGE/DTEC/DPRQ/DMES): Modelagem hidráulica, simulações de capacidade instalada e estimativa orçamentária do CAPEX futuro, protegendo o indicador ISP. Emitem um Laudo Técnico de Viabilidade, detalhando se a infraestrutura suporta a nova procura. (GRMC): Parecer de viabilidade ou, estrategicamente, formaliza objeção regulatória com o intuito de travar exigências abusivas de expansão que não tenham cobertura tarifária. Saída (GAPR): Parecer de Viabilidade ou Objeção remetido à AGRESE e a Concessionária. (SPGE/SFCC): Monitoramento de Eficiência de CAPEX Forçado (Estas unidades devem acompanhar financeiramente a performance de vendas da Concessionária nas zonas onde a DESO foi obrigada a expandir. Caso a demanda projetada não se materialize, deve-se peticionar à AGRESE a execução da Cláusula 10.5.3, cobrando o ressarcimento estrutural)."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Produção (Eixo 2)",
    "id": "2.3",
    "processo": "Fiscalização do Padrão de Potabilidade (IQA)",
    "fundamentacao": "Cláusula 9.3 e 9.5 do Contrato de Interdependência; 18.2  do Contrato de Produção de Água",
    "fluxo": "SQCO → Processo 2.1",
    "destino": "AGRESE / Concessionária",
    "prazo": "Mensalmente, até o 5º dia do mês subsequente.",
    "impacto": "Multa direta de 1% do faturamento; além da Concessionária utilizar a denúncia à lide para transferir à DESO indenizações cíveis movidas por contaminação de usuários finais.",
    "entregaveis": "(SQCO): Certificados de análises laboratoriais com o somatório de medições de cloro residual livre, turbidez, cor e pH (variáveis QD006 e QD007) atestando estatisticamente o atingimento da meta de IQA, incorporados ao Relatório Mensal do Processo 2.1."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Produção (Eixo 2)",
    "id": "2.4",
    "processo": "Comunicação de Paradas Programadas de Manutenção e Obras de Aperfeiçoamento do Sistema Upstream",
    "fundamentacao": "Cláusula 10.13 do Contrato de Interdependência; Cláusula 18.2 do Contrato de Produção; Ofício nº 212/2026-AGRESE",
    "fluxo": "SGAT → GRMC → GAPR",
    "destino": "Concessionária / AGRESE",
    "prazo": "Antecedência mínima de 02 dias úteis (se durar > 3 horas) para Concessionária. / Antecedência mínima de 24 horas para AGRESE.",
    "impacto": "Caracterização de desabastecimento culposo, impedindo manobras de contingência na rede Downstream. Inflação severa do DMP. Ausência de provas, resultando no cômputo da água retida como Volume Não Fornecido (VN), autorizando a CONCESSIONÁRIA a incluir e calcular os valores correspondentes na Equação D, mediante validação posterior da AGRESE.",
    "entregaveis": "(DTEC/DPRQ - Obras de Aperfeiçoamento do Sistema): Relatório com Plano de Mitigação de Paralisação atrelado aos projetos executivos, elaborado em conjunto pelas Diretorias Técnica e de Produção.  (SGAT - Paradas Programadas): Relatório técnico contendo, imperativamente: o planejamento estratégico adotado para mitigação dos impactos no abastecimento; o escopo detalhado da realização das manobras operacionais contingenciais; a estimativa temporal de duração dos serviços; e o mapeamento dos sistemas potencialmente atingidos nas regiões afetadas. (GRMC): Certificação de cumprimento de prazo de aviso contratual. Saída (GAPR): Ofício formal de comunicação de interrupção autorizada e programada, isentando o cômputo no DMP e no VN."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Produção (Eixo 2)",
    "id": "2.5",
    "processo": "Notificação de Redução Operacional Emergencial",
    "fundamentacao": "Cláusula 10.12.1 do Contrato de Interdependência",
    "fluxo": "DPRQ → GRMC → GAPR / GRMC → SFCC",
    "destino": "AGRESE / Concessionária",
    "prazo": "Imediato, quando a redução for ≥ 10% do fluxo contratado e durar > 12 horas.",
    "impacto": "Dedução dos valores correspondentes Equação D (VN - Volume não fornecido). Multa de até 1% (um por cento) do valor da fatura do mês de ocorrência da infração.",
    "entregaveis": "Dedução dos valores correspondentes Equação D (VN - Volume não fornecido). Multa de até 1% (um por cento) do valor da fatura do mês de ocorrência da infração. (DPRQ): Parecer de anomalia emergencial contendo os dados operacionais e o déficit volumétrico, o planejamento imediato de manobras operacionais contingenciais, a estimativa do tempo de reparo e os sistemas secundários atingidos, em alinhamento com a diretriz da AGRESE. (GRMC): Análise de enquadramento da contingência como evento excludente (Força Maior), com emissão de Nota Técnica provando o Evento Excludente.  Saída (GAPR): Declaração de redução operacional emergencial à CONCESSIONÁRIA e à AGRESE, pleiteando legalmente que eles excluam o volume dos cálculos futuros que vierem a elaborar."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Produção (Eixo 2)",
    "id": "2.6",
    "processo": "Acompanhamento de Vistorias de Qualidade e Intermitências (Certificador)",
    "fundamentacao": "Cláusula 9.7, 9.7.5 e 9.7.6 do Contrato de Interdependência",
    "fluxo": "SQCO / SPRO → GRMC → GAPR",
    "destino": "Certificador Independente / AGRESE",
    "prazo": "Contínuo.",
    "impacto": "Determinação de responsabilidade de obras emergenciais em prazos limitados.",
    "entregaveis": "(SQCO/SPRO): Relatórios operacionais e laboratoriais detalhados contendo os controles de qualidade da água (IQA), registros de pressão das grandes adutoras (ISP) e as evidências de manutenções regulares e os tempos de paralisação (DMP). (GRMC): Defesa regulatória para contestar falhas metodológicas do laudo ou absorver determinações de melhoria do Certificador. Saída (GAPR): Respostas formais aos achados de conformidade, protocoladas perante o Certificador e a Agência Reguladora."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.1",
    "processo": "Envio do Cronograma de Obras de Aperfeiçoamento do Sistema Upstream",
    "fundamentacao": "Cláusula 10.1 do Contrato de Produção de Água",
    "fluxo": "SPGE / SUEN → GRMC → GAPR",
    "destino": "AGRESE / Poder Concedente / Municípios",
    "prazo": "Contínuo. Atualizado nas revisões quinquenais.",
    "impacto": "Infração administrativa.",
    "entregaveis": "(SPGE/SUEN): Relatórios de modelagem de obras, cronogramas e projeções de desembolso (CAPEX) com detalhamento por Município. (GRMC): Verificação de compliance e prazo regulatório. Saída (GAPR): Cronograma Final protocolado na AGRESE e Poder Concedente. (GAPR): Publicação no site da DESO do cronograma de intervenções programadas nos Municípios, com antecedência mínima de 30 dias para o seu início."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.2",
    "processo": "Submissão de Projetos Básicos/Executivos (Obras de Aperfeiçoamento do Sistema Upstream)",
    "fundamentacao": "Cláusula 10.5 do Contrato de Produção de Água",
    "fluxo": "SUEN → GRMC → GAPR",
    "destino": "AGRESE",
    "prazo": "Antecedência de 90 dias antes do início da obra.",
    "impacto": "Execução sem autorização gera embargo ambiental/operacional e pode obrigar a DESO a refazer a infraestrutura inteira sem direito a cobrar os custos adicionais (Retenção de risco pela Cláusula 21.3.12).",
    "entregaveis": "(SUEN): Memoriais descritivos exaustivos, plantas CAD tratadas, especificações técnicas, Anotações de Responsabilidade Técnica (ART’s) e orçamentos, conforme requisitos de projeto (Básico ou Executivo). (GRMC): Checagem de licenciamento ambiental prévio e conformidade. Saída (GAPR): Encaminha pacotes de projetos para análise regulatória."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.3",
    "processo": "Entrega de Desenhos As-Built (Obras de Aperfeiçoamento do Sistema Upstream)",
    "fundamentacao": "Cláusula 10.12 do Contrato de Produção de Água",
    "fluxo": "SUEN → GRMC → GAPR / GRMC → SFCC",
    "destino": "AGRESE / Poder Concedente",
    "prazo": "Até 90 dias após a conclusão da obra.",
    "impacto": "Até 90 dias após a conclusão da obra.",
    "entregaveis": "Infração administrativa. Defasagem na Base de Ativos (BAR) que inviabilizam compensações futuras e depreciação fiscal. (SUEN):  Laudos de qualidade dos materiais e ateste de comissionamento de 100% da execução física. Cópias finais consolidadas e assinadas (ART’s) das plantas As-Built). (GRMC): Checagem dos requisitos contratuais e comunicação à SFCC para registro patrimonial e depreciação fiscal. Saída (GAPR): Protocolo com entrega de 3 vias físicas e mídias eletrônicas, na AGRESE  e Poder Concedente."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.4",
    "processo": "Notificação de Conclusão - Obras da Concessão (Anexo IV)",
    "fundamentacao": "Cláusula 11.4 do Contrato de Produção de Água",
    "fluxo": "SUEN → GRMC → GAPR",
    "destino": "Certificador Independente / Concessionária",
    "prazo": "Antecedência de 30 dias do término estimado.",
    "impacto": "Se atraso > 6 meses, assunção forçada da obra pela Concessionária com reequilíbrio contra a DESO.",
    "entregaveis": "(SUEN): Relatório informando a finalização iminente da execução física com indicação de data para vistoria conjunta, acompanhado de relatórios fotográficos de evolução, projetos de engenharia, especificações técnicas, manuais de equipamentos, “databooks”, licenças, autorizações e outorgas, inclusive ambientais, referentes às fases de projetos.  (GRMC): Checagem de todos requisitos contratuais.  Saída (GAPR): Ofício de Aviso de Conclusão e Convocação para Vistoria."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.5",
    "processo": "Manifestação sobre Laudo do Certificador Independente",
    "fundamentacao": "Cláusula 11.4.6 do Contrato de Produção de Água",
    "fluxo": "DTEC → GRMC → GAPR",
    "destino": "Certificador Independente / AGRESE",
    "prazo": "Até 30 dias do recebimento do relatório.",
    "impacto": "Preclusão do direito de defesa; imposição sumária de refazimento.",
    "entregaveis": "(DTEC): Relatório Técnico Evidencial exaustivo, destinado a contestar parcial/integralmente ou acatar os apontamentos do Certificador. O documento deve ser instruído com memórias de cálculo revisadas, ensaios laboratoriais dos materiais, sondagens geotécnicas e registros fotográficos georreferenciados que demonstrem a lisura construtiva. (GRMC): Parecer de mitigação de risco regulatório atestando o enquadramento da defesa nos limites do contrato. Saída (GAPR): Ofício de Defesa/Resposta oficial submetido ao Certificador, à AGRESE e Poder Concedente."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.6",
    "processo": "Atualização do Status de Execução - Relatórios de Acompanhamento Externo",
    "fundamentacao": "Cláusulas 10 e 11 do Contrato de Produção de Água.",
    "fluxo": "SUEN → GRMC → GAPR",
    "destino": "AGRESE / Poder Concedente",
    "prazo": "Mensalmente, até o 10º dia corrido do mês subsequente.",
    "impacto": "Revelia em processos regulatórios; aplicação de multas administrativas, sanções pecuniárias contratuais.",
    "entregaveis": "(SUEN): Relatório Técnico e Planilhas com atualização dos percentuais de avanço físico das obras (Anexo XIV e Obras de Aperfeiçoamento Upstream). (GRMC): Análise de conformidade e prazos. Saída (GAPR): Ofício de Resposta oficial submetido ao Poder Concedente e à AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.7",
    "processo": "Celebração do Termo de Transferência da Obra",
    "fundamentacao": "Cláusula 11.5 do Contrato de Produção de Água",
    "fluxo": "SUEN → SJUR → SFCC → GAPR",
    "destino": "Concessionária",
    "prazo": "Ato contínuo à aprovação final pelo Certificador.",
    "impacto": "Responsabilidade civil contínua e não reconhecimento de avanço da meta.",
    "entregaveis": "(SUEN): Relatório de Comissionamento Consolidado contendo a declaração de aprovação final do Certificador (Processo 3.4). (SJUR): Minuta revisada do instrumento de transferência. (SFCC): Conciliação prévia da Base de Ativos para registro contábil de baixa ou transferência. (GRMC): Certificação de superação de todas as condicionantes regulatórias. Saída (GAPR): Termo de Transferência da Obra (TTO) formalmente assinado pelos representantes legais e averbado."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.8",
    "processo": "Entrega de Desenhos As-Built Obras da Concessão (Anexo IV)",
    "fundamentacao": "Cláusula 11.7 do Contrato de Produção de Água",
    "fluxo": "SUEN → GRMC → GAPR",
    "destino": "Concessionária",
    "prazo": "Até 90 dias após a assinatura do Termo de Transferência.",
    "impacto": "Quebra de obrigações acessórias do repasse do ativo com infração administrativa.",
    "entregaveis": "(SUEN): Acervo Técnico Integral contendo cópias consolidadas (vinculadas às respectivas ART’s) das plantas As-Built, esquemas elétricos e hidráulicos finais, e todos os manuais de projeto, operação e manutenção preventiva dos equipamentos instalados. (GRMC): Checagem do cumprimento dos requisitos documentais e prazos regulatórios. Saída (GAPR): Ofício de entrega do acervo técnico integral à Concessionária (3 mídias eletrônicas completas)."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.9",
    "processo": "Resolução de Vícios Construtivos e Ocultos",
    "fundamentacao": "Cláusula 11.5.1 a 11.5.4 do Contrato de Produção de Água",
    "fluxo": "DTEC (SJUR e SFCC) → GRMC → GAPR",
    "destino": "Certificador Independente / Concessionária",
    "prazo": "Testes: 180 dias.  Garantia geral: 5 anos (Art. 618 CC).",
    "impacto": "Risco financeiro absoluto suportado pela DESO (Cláusula 21.3.25).",
    "entregaveis": "(DTEC): Plano de Ação Corretiva (PAC) pormenorizado contendo o escopo da intervenção de engenharia civil/eletromecânica, cronograma de execução do reparo mitigando paralisações de fluxo, emissão de novas ART’s de correção e laudos de funcionalidade emitidos pós-intervenção. Quando couber, com auxílio da SJUR/SFCC  realizar o acionamento direto do seguro garantia das empreiteiras e a execução do direito de regresso. Uma vez sanado, é emitido pela DTEC o Relatório Conclusivo de Saneamento do Vício submetido. (GRMC): Análise de conformidade contratual. Saída (GAPR): Envio do relatório final para validação do Certificador e da Concessionária."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.10",
    "processo": "Procedimento de Desapropriação e Servidão (DUP)",
    "fundamentacao": "Cláusulas 15.3.1 e 15.5.1 do Contrato de Produção de Água",
    "fluxo": "DTEC → SJUR → GRMC",
    "destino": "Poder Concedente",
    "prazo": "Por demanda.",
    "impacto": "Atraso imputado à DESO se o dossiê for deficiente; se houver mora estatal, gatilho de reequilíbrio.",
    "entregaveis": "(DTEC): Relatório Fundiário Exaustivo composto por levantamentos planialtimétricos, cadastro georreferenciado detalhado de proprietários e superficiários e laudos periciais de avaliação mercadológica dos imóveis. (SJUR): Minuta prévia do Decreto de Utilidade Pública. (GRMC): Nota Técnica Regulatória mapeando o risco de atraso na imissão de posse, constituindo evidência primária de eventual Fato da Administração. Saída (GAPR): Requerimento formal de DUP protocolado no Poder Concedente e consolidação do Programa de Trabalho conjunto."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.11",
    "processo": "Transferência e Cessão de Direitos de Propriedade Intelectual",
    "fundamentacao": "Cláusula 32 e 32.1 do Contrato de Produção de Água",
    "fluxo": "Crivo legal da SJUR / GLIC.",
    "destino": "SUEN (para obras) / GTIC (para inovações digitais) → SJUR → SFCC → GCIG",
    "prazo": "Poder Concedente/ Municípios (futuramente)",
    "impacto": "Contínuo. Sem data fixa; inicia-se na licitação e consolida-se sempre que um ciclo de investimento ou projeto é concluído.",
    "entregaveis": "Autuação regulatória por obstrução e dificultação da reversibilidade da concessão,  inviabilização da correta alocação dos intangíveis na Base de Ativos Regulatória (BAR). (SJUR/GLIC): Termo de Referência e no Edital Licitatório com as cláusulas obrigatórias de cessão plena, irrestrita e inalienável de todos os direitos patrimoniais vinculados ao projeto/software em desenvolvimento. (SUEN/GTIC): Projetos básicos, executivos e As-Built (BIM, DWG/CAD, PDF/A); ART’s recolhidas; rotinas de software e bases GIS; finalizados e entregues. (SJUR): Emissão de Parecer Jurídico de Renúncia. (SFCC): Registro/contabilização dos ativos na BAR. (GCIG): Análise e atualização das matrizes de risco."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.12",
    "processo": "Reintegração Física e Contábil de Infraestruturas de Emergência (Micro-ETAs/Poços)",
    "fundamentacao": "Cláusulas 10.6.3 do Contrato de Interdependência",
    "fluxo": "DTEC / DPRQ → SJUR → SFCC → GRMC → GAPR",
    "destino": "Concessionária",
    "prazo": "Em até 6 meses contados do início da operação emergencial e autônoma pela Iguá.",
    "impacto": "Perda velada da exclusividade e monopólio legal de captação; infraestrutura de valor eliminada da  proteção patrimonial; descompasso contábil e desordem volumétrica impune.",
    "entregaveis": "(DTEC/DPRQ): Laudo extensivo de comissionamento reverso (vistoriando o estado civil, elétrico e químico do ativo entregue pela Concessionária). (SJUR): Termo de Recebimento Definitivo de Ativo Emergencial devidamente assinado. (SFCC): Tombamento físico e incorporação atuarial na BAR. (GRMC): Análise de conformidade regulatória. Saída (GAPR): Protocolo na AGRESE para ateste do fim da intermitência e incorporação do ativo."
  },
  {
    "eixo": "Matriz Processual de Conformidade de Investimentos (Eixo 3)",
    "id": "3.13",
    "processo": "Plano de Desmobilização e Reversão (Fim da Concessão)",
    "fundamentacao": "Cláusula 31.5 e 24.5 do Contrato de Produção de Água",
    "fluxo": "SPGE / DTEC / DPRQ / SFCC → GRMC → SJUR → GAPR",
    "destino": "Poder Concedente / AGRESE",
    "prazo": "1 ano antes do fim do contrato (ou 75 dias em rescisão).",
    "impacto": "Indenizações retidas ou questionadas pelo regulador.",
    "entregaveis": "(SPGE/DTEC/DPRQ/SFCC): Programa de Desmobilização Operacional com Plano de Transição, contendo inventário físico-contábil de Bens Reversíveis metodologicamente estruturado sob os ditames da contabilidade regulatória, contendo balancetes de depreciação acumulada, laudos de conservação estrutural atualizados e apuração atuarial dos saldos residuais não amortizados da BAR. (GRMC): Nota Técnica Regulatória atestando a conformidade do pacote com as normativas de prestação de contas da AGRESE e normas de referência da ANA. (SJUR): Análise jurídica e aprovação do Plano de Transição. Saída (GAPR): Plano Oficial de Desmobilização submetido à Agência Reguladora e ao Poder Concedente para homologação da indenização de capital."
  },
  {
    "eixo": "Matriz Processual de Conformidade Institucional (Eixo 4)",
    "id": "4.1",
    "processo": "Acionamento do Comitê Técnico (Conflitos: DESO x Poder Concedente)",
    "fundamentacao": "Cláusulas 34.8 e 34.9 do Contrato de Produção de Água",
    "fluxo": "Diretoria pertinente à divergência / SJUR → GRMC → GAPR",
    "destino": "Comitê Técnico / Poder Concedente",
    "prazo": "Por demanda (Réu manifesta em 15 dias; Comitê decide em 30 dias).",
    "impacto": "Resolução de conflito adiado com prejuízos operacionais.",
    "entregaveis": "(Diretoria Demandante/SJUR): Requerimento Técnico exaustivo, contendo fundamentação normativa, laudos periciais e toda documentação necessária para  fundamentar o relatório e as alegações nele contidas. (GRMC): Enquadramento da demanda nos limites interpretativos do contrato. Saída (GAPR): Submissão formal da controvérsia técnica aos membros do Comitê Técnico."
  },
  {
    "eixo": "Matriz Processual de Conformidade Institucional (Eixo 4)",
    "id": "4.2",
    "processo": "Instauração e Condução de Arbitragem (Conflitos: DESO x Concessionária)",
    "fundamentacao": "Cláusula 17 do Contrato de Interdependência",
    "fluxo": "GRMC → Diretoria pertinente à divergência / SJUR → GAPR",
    "destino": "CAM-CCBC (Câmara de Comércio Brasil-Canadá)",
    "prazo": "Por demanda, após exaurida tentativa de mediação.",
    "impacto": "Custos transacionais altíssimos e risco sentencial definitivo.",
    "entregaveis": "(Diretoria Demandante/SJUR): Petição Inicial de Requerimento de Arbitragem com delimitação clara e exaustiva dos pedidos, anexação de provas documentais e indicação de assistentes técnicos especializados quando necessário. (GRMC): Nota Técnica Regulatória prévia demonstrando a falência e o esgotamento da via conciliatória. Saída (GAPR): Protocolo de instauração de arbitragem na Câmara (CCBC)."
  },
  {
    "eixo": "Matriz Processual de Conformidade Institucional (Eixo 4)",
    "id": "4.3",
    "processo": "Notificação de Evento de Força Maior ou Caso Fortuito",
    "fundamentacao": "Cláusula 22.15 e 29 do Contrato de Produção de Água",
    "fluxo": "Diretoria da ocorrência do evento / GCIG → GRMC → GAPR",
    "destino": "Poder Concedente / Concessionária",
    "prazo": "Em até 48 horas após a ocorrência do evento.",
    "impacto": "Perda do direito à excludente de responsabilidade, absorvendo todo o risco financeiro.",
    "entregaveis": "(Diretoria Demandante/GCIG): Relatório de Evento Crítico Circunstanciado detalhando tecnicamente a origem do fortuito (fatores imprevisíveis internos) ou força maior (fatores imprevisíveis externos), o tempo exato da parada de sistema e a documentação do plano de mitigação/contingência executado em tempo real. (GRMC): Nota Técnica Regulatória correlacionando o evento ao rol restritivo de excludentes contratuais válidas. Saída (GAPR): Ofício de Urgência de Declaração Oficial de Caso Fortuito ou de Força Maior."
  },
  {
    "eixo": "Matriz Processual de Conformidade Institucional (Eixo 4)",
    "id": "4.4",
    "processo": "Pleito de Reequilíbrio Econômico-Financeiro",
    "fundamentacao": "Cláusula 21.11 do Contrato de Produção de Água",
    "fluxo": "GCIG / SPGE / SFCC → GRMC → GAPR",
    "destino": "AGRESE / Poder Concedente",
    "prazo": "Imediato à materialização ou iminência do risco. Agrese notifica em 5 dias; outra parte responde em 60 dias; decisão final em 120 dias.",
    "impacto": "Ruína financeira, perda do valor de investimento e descompasso tarifário.",
    "entregaveis": "(GCIG/SPGE/SFCC): Relatório técnico ou laudo pericial que demonstre os impactos e repercussões do evento de desequilíbrio sobre os custos e receitas e os efeitos econômico-financeiros do evento de desequilíbrio, por meio de previsões elaboradas especificamente para sua demonstração, considerando os fluxos marginais resultantes do evento que deu origem à recomposição e  os fluxos marginais necessários para a recomposição do equilíbrio econômico-financeiro (Dossiê Atuarial, Orçamentário e de Custos contendo a modelagem financeira do evento de risco materializado, planilhas de Fluxo de Caixa Marginal projetado, etc.). (GRMC): Instrução regulatória defensiva e enquadramento contratual do pleito. Saída (GAPR): Pleito Formal de Reequilíbrio Econômico-Financeiro encaminhado a AGRESE e Poder Concedente."
  },
  {
    "eixo": "Matriz Processual de Conformidade Institucional (Eixo 4)",
    "id": "4.5",
    "processo": "Defesa Prévia Contra Autos de Infração e Multas",
    "fundamentacao": "Cláusula 22.4 e 22.6 do Contrato de Produção de Água; 15 do Contrato de Interdependência",
    "fluxo": "GRMC → Diretoria responsável / SJUR / GCIG → PR / SFCC → GRMC → GAPR",
    "destino": "AGRESE",
    "prazo": "30 dias para defesa; 15 dias para recurso (efeito suspensivo).",
    "impacto": "Punição financeira.",
    "entregaveis": "(GRMC): Análise do auto de infração e encaminhamento para deliberação da Diretoria responsável em conjunto com SJUR e GCIG. (Diretoria responsável/SJUR/GCIG): Peça de Defesa Administrativa, instruída com métricas comprovando a estrita conformidade operacional, ou, caso a infração seja inconteste, demonstrando inequivocamente a aplicação de fatores atenuantes (como adoção espontânea e prévia de reparos de danos) para pleitear os descontos progressivos de 5% a 10% previstos na cláusula de dosimetria. A decisão de Litígio vs. Acordo deve ser tomada em conjunto com a SFCC e a Presidência. (GRMC): Análise regulatória de toda a Peça de Defesa e dosimetria aplicável. Saída (GAPR): Protocolo da Petição de Defesa formalizada na AGRESE."
  },
  {
    "eixo": "Matriz Processual de Conformidade Institucional (Eixo 4)",
    "id": "4.6",
    "processo": "Tratamento da Obstrução de Instalações e Dados",
    "fundamentacao": "Cláusula 5.6 e 15.1.1 do Contrato de Interdependência",
    "fluxo": "Equipe demandante → OUVI → GRMC → GAPR",
    "destino": "AGRESE",
    "prazo": "Denúncia imediata.",
    "impacto": "Multa mútua de até 1% do faturamento da fatura pela obstrução.",
    "entregaveis": "(Equipe afetada): Denúncia (não anônima) no canal de Ouvidoria, contendo toda documentação comprobatória necessária.   (Ouvidoria): Auto de Constatação formal e circunstanciado descrevendo minuciosamente a negativa de acesso ao perímetro operacional alheio, devidamente consubstanciado por anexos contendo e-mails não respondidos, vídeos ou registros formais das tentativas frustradas de acesso de campo ou de dados. (GRMC): Solicitação administrativa de intervenção e aplicação da sanção contratual cabível. Saída (GAPR): Denúncia Formal de Obstrução de Acesso protocolada na Agência Reguladora."
  },
  {
    "eixo": "Matriz Processual de Conformidade Institucional (Eixo 4)",
    "id": "4.7",
    "processo": "Reporte de Conformidade Laboral e Inclusão Social (Cota PCD’s)",
    "fundamentacao": "Cláusula 33.2 do Contrato de Produção de Água / Lei Federal nº 8.123/1991",
    "fluxo": "SGPE",
    "destino": "AGRESE / Poder Concedente",
    "prazo": "Anualmente, até o último dia de março.",
    "impacto": "Descumprimento da função social do contrato, com infração administrativa e a aplicação de multa.",
    "entregaveis": "(SGPE): Relatório de Censo Demográfico Corporativo atestando matematicamente e contabilmente o preenchimento legal satisfatório de vagas por Pessoas com Deficiência (PCD), com memórias de cálculo percentuais ancoradas no efetivo total. (GRMC): Análise de conformidade regulatória."
  },
  {
    "eixo": "Matriz Processual de Conformidade Institucional (Eixo 4)",
    "id": "4.8",
    "processo": "Emissão de Nota de Inconformidade Regulatória (Atrasos com impactos externos)",
    "fundamentacao": "Cláusulas contratuais gerais de prazos de prestação de contas, respostas a ofícios e diligências.",
    "fluxo": "GRMC → GAPR / PR → Diretoria responsável",
    "destino": "PRES e Diretorias Responsáveis pelo atraso",
    "prazo": "Imediato (Até 1 dia útil após a constatação do vencimento do prazo externo).",
    "impacto": "Revelia em processos regulatórios; aplicação de multas administrativas, sanções pecuniárias contratuais e prejuízo ao equilíbrio econômico-financeiro da DESO por omissão ou inércia estrutural.",
    "entregaveis": "(GRMC): Emissão formal da Nota de Inconformidade Regulatória, documento detalhando o prazo vencido, a obrigação infringida, as penalidades iminentes e a exigência de um Plano de Ação Corretivo. Esta Nota de Inconformidade será emitida para a Presidência/GAPR, que providenciará as diligências internas. Saída (GAPR): Despacho institucional imediato da Nota de Inconformidade para as Diretorias responsáveis, impondo a resolução do atraso em caráter de urgência."
  }
];
